def glosarium():
    return {
    "tren":{
        # "periode":"year on year, year to date", "year on year artinya data diambil merupaka agregasi 12 bulan penuh", "year to date artinya data merupakan agregasi selama tahun berjalan",
        "as_of_date":"tanggal terakhir suatu bulan berdasarkan periode yang dipilih, misalkan 20230930 artinya tahun 2023, bulan 09 atau september, tanggal 30",
        "flag_trx":"jenis tren meliputi: CASA atau Current Account and Savings Account,cash in atau pemasukan, cash out atau pengeluaran, closedloop atau feedback, co intra vs co total",
        "variable":"variabel tren meliputi: eom atau end of month, mtd atau month to date, avg interbank/average interbank, avg interbank, interbank, intrabank, ytd atau year to date",
        "divisi_kelolaan":"divisi kelolaan, divisi, unit kelolaan",
        "group_corporate":"group corporate, grup perusahaan, grup",
        "bulan1":"besarnya nilai pada bulan pertama dalam periode, 11 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan1":"nama bulan pertama dalam periode, 11 bulan sebelum bulan saat ini berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan2":"besarnya nilai pada bulan kedua dalam periode, 10 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan2":"nama bulan kedua dalam periode, 10 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan3":"besarnya nilai pada bulan ketiga dalam periode, 9 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan3":"nama bulan ketiga dalam periode, 9 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan4":"besarnya nilai pada bulan keempat dalam periode, 8 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan4":"nama bulan keempat dalam periode, 8 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan5":"besarnya nilai pada bulan kelima dalam periode, 7 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan5":"besarnya nilai pada bulan kelima dalam periode, 7 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan5":"nama bulan kelima dalam periode, 7 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan6":"besarnya nilai pada bulan keenam dalam periode, 6 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan6":"nama bulan keenam dalam periode, 6 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan7":"besarnya nilai pada bulan ketujuh dalam periode, 5 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan7":"nama bulan ketujuh dalam periode, 5 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan8":"besarnya nilai pada bulan kedelapan dalam periode, 4 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan8":"nama bulan kedelapan dalam periode, 4 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan9":"besarnya nilai pada bulan kesembilan dalam periode, 3 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan9":"nama bulan kesembilan dalam periode, 3 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan10":"besarnya nilai pada bulan kesepuluh dalam periode, 2 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan10":"nama bulan kesepuluh dalam periode, 2 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan11":"besarnya nilai pada bulan kesebelas dalam periode, 1 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan11":"nama bulan kesebelas dalam periode, 1 bulan sebelum as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "bulan12":"besarnya nilai pada bulan keduabelas dalam periode, sama dengan as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "namabulan12":"nama bulan keduabelas dalam periode, sama dengan as_of_date berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "mean_value":"nilai rata-rata dari keseluruhan nilai tiap bulan yang diambil berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "min_value":"Nilai terendah dari keseluruhan nilai tiap bulan yang diambil berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "max_value":"Nilai tertinggi dari  keseluruhan nilai tiap bulan yang diambil berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "max_bulan":"Bulan dengan nilai tertinggi dari keseluruhan nilai tiap bulan yang diambil berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        "min_bulan":"Bulan dengan nilai terendah dari keseluruhan nilai tiap bulan yang diambil berdasarkan periode, as_of_date, flag_trx, variable, divisi_kelolaan, dan group_corporate terkait",
        #flag trx
        "closedloop":"closed-loop transactions percentage", #: ratio of cash out intrabank to total cash in
        "CASA":"current account savings account (tabungan dan giro)",
        "cash in":"cash in (aliran uang masuk)",
        "cash out":"cash out (aliran uang keluar)",
        "co vs co nanti isi lagi":'ratio of cash out intrabank to total cash out',
        #variable
        "ytd":"year-to-date",
        "eom":"end-of-month",
        "mtd":"average in that month (month-to-date)",
        "interbank":"different bank (keluar bank)",
        "intrabank":"same bank (dalam bank, BNI)"
    },
    "list cif":{
        "grup":"group corporate, grup perusahaan. grup",
        "divisi":"divisi kelolaan, divisi, unit kelolaan",
        "cif_key":"cif (Customer Information File) merupakan identitas unik nasabah BNI. cif sesuai grup yang dipilih",
        "nama_entitas":"nama entitas yang terdaftar di BNI. Satu entitas bisa jadi memiliki lebih dari 1 cif. nama entitas merupakan entitas yang terdapat di dalam grup yang dipilih",
        "posisi_saldo_eom":"posisi saldo end of month, posisi saldo terakhir dari cif_key dalam bulan yang dipilih",
        "avg_saldo_ytd":"average saldo year to date, rata-rata saldo harian sejak awal tahun / sejak awal tahun ini / dari awal tahun / dari awal tahun Ini dari cif_key",
        "baki_debet_eom":"baki debet di end of month / akhir bulan terkait dari cif_key. Menandakan besaran nominal kredit dari cif_key terkait.",
        "avg_baki_debet_ytd":"rata-rata baki debet harian di tahun berjalan dari cif_key",
        "maksimum_kredit":"nilai maksimum / batas paling besar kredit dari cif_key",
        "utilisasi_kredit":"didapat dengan membagi baki_debet_eom dengan maksimum kredit. menandakan berapa persen potensi kredit dari cif_key yang telah digunakan",
        "ldr_eom":"loan to deposit ration. menunjukkan perbandingan antara baki_debet_eom (baki debet cif_key) dengan posisi_saldo_eom (saldo dpk cif_key). nilai ldr yang tinggi mengindikasikan cif_key memiliki lebih banyak hutan dibandingkan asetnya di BNI",
        "ldr_ytd":"loan to deposit ration. menunjukkan perbandingan antara avg_baki_debet_ytd (rata rata baki debet harian cif_key selama tahun berjalan) dengan avg_saldo_ytd (rata rata saldo dpk harian cif_key selama tahun berjalan). nilai ldr yang tinggi mengindikasikan cif_key memiliki lebih banyak hutan dibandingkan asetnya di BNI",
        "flag_debitur":"bernilai 1 atau 0. 1 artinya cif_key tersebut telah memiliki kredit / loan di BNI",
        "flag_payroll":"bernilai 1 atau 0. 1 artinya cif_key tersebut telah berpayroll BNI",
        "rn":"urutan cif_key pada grup yang dipilih. diurutkan dari yang memiliki saldo dpk (posisi_saldo_eom) tertinggi",
        "as_of_date":"tanggal terakhir suatu bulan berdasarkan periode yang dipilih, misalkan 20230930 (tahun 2023, bulan 09 atau september, tanggal 30)"
    },
    "value chain":{
        "periode":"year on year, year to date. year on year artinya data diambil merupaka agregasi 12 bulan penuh. year to date artinya data merupakan agregasi selama tahun berjalan",
        "tanggal":"tanggal terakhir suatu bulan berdasarkan periode yang dipilih, misalkan 20230930 (tahun 2023, bulan 09 atau september, tanggal 30). sama dengan as_of_date",
        "nama_group":"group corporate, grup perusahaan. grup",
        "divisi_kelolaan":"divisi kelolaan, divisi, unit kelolaan",
        "frekuensi_cash_in":"frekuensi cash in / frekuensi transaksi masuk / jumlah transaksi yang masuk dari grup yang masuk berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
        "volume_cash_in":"volume cash in / volume transaksi masuk / nominal transaksi yang masuk dari grup berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
        "frekuensi_cash_out":"frekuensi cash out / frekuensi transaksi keluar / jumlah transaksi yang keluar dari grup berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
        "volume_cash_out":"volume cash out / volume transaksi keluar / nominal transaksi yang keluar dari grup berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
        "posisi_saldo_eom":"posisi saldo end of month, posisi saldo terakhir dari grup berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
        "avg_saldo_ytd":"average saldo year to date, rata-rata saldo harian sejak awal tahun / sejak awal tahun ini / dari awal tahun / dari awal tahun Ini dari grup berdasarkan periode, tanggal, nama_group, dan divisi_kelolaan terkait",
    }
}
